name: "build and debloy"

on:
    push:
        branches:
            - main

permissions:
    checks: write
    contents: write

jobs:
    run-linters:
        name: Run linters
        runs-on: ubuntu-latest
        steps:
          - name: Check out Git repository
            uses: actions/checkout@v2

          - name: Set up Node.js
            uses: actions/setup-node@v1
            with:
              node-version: 16

          - name: Set up go
            uses: actions/setup-go@v3
            with:
                go-version: '>=1.17.0'

          - name: Install Node.js and bulid
            run: |
              npm install -g npm@latest
              npm i
              npm run build
            working-directory: ./frontend

          - name: Run build
            run: |
              go version
              go build
            working-directory: ./cmd/api
