name: "build and debloy"

on:
    push:
        branches:
            - main

permissions:
    checks: write
    contents: write

jobs:
    run-build:
        name: Run build
        runs-on: ubuntu-latest
        steps:
          - name: Check out Git repository
            uses: actions/checkout@v2

          - name: Set up Node.js
            uses: actions/setup-node@v1
            with:
              node-version: 16

          - name: Set up go
            uses: actions/setup-go@v3
            with:
                go-version: '>=1.17.0'

          - name: Install Node.js and bulid
            run: |
              npm install -g npm@latest
              npm i
              npm run build
            working-directory: ./frontend

          - name: Run build
            run: |
              go version
              ls -la ../../frontend/public
              ls -la ../../frontend/public/build
              go build
              ls -la ./api
            working-directory: ./cmd/api
          - name: Setup ssh
            uses: shimataro/ssh-key-action@v2
            with:
              key: ${{ secrets.SSH_KEY }}
              name: id_ed25519
              known_hosts: ${{ secrets.KNOWN_HOSTS }}
              if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
          - name: Run deploy
            run: |
              ls -la ./api
              scp -P${{ secrets.SSH_PORT }} ./api ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}:api
              ssh -p${{ secrets.SSH_PORT }}  ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} "sudo /opt/inet-ip.info/deploy.sh"
            working-directory: ./cmd/api
